name: Build and Test Windows Bundle

on:
  pull_request:
    branches: [ master ]

jobs:
  # Build the bundles
  bundle-win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: bash ./scripts/bundle-win.sh
    - name: Archive bundle
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Compress-Archive bundles/bundle-win bundle-win.zip
        azPSVersion: '3.1.0'
    - name: Display directory structure of bundle
      run: ls -R ./bundles/bundle-win
    - name: Upload bundle
      uses: actions/upload-artifact@v2
      with:
        name: bundle-win
        path: |
          ./bundle-win.zip

  # Download and test the bundle on another machine and test it
  test-win:
    runs-on: windows-latest
    needs: bundle-win
    steps:
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Download bundle
      uses: actions/download-artifact@v2
      with:
        name: bundle-win
        path: artifacts/
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: artifacts/
    - name: Unarchive bundle
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Expand-Archive -Path ./artifacts/bundle-win.zip -DestinationPath ./artifacts/
        azPSVersion: '3.1.0'
    - name: Display structure of decompressed files
      run: ls -R
      working-directory: artifacts/
    - name: Set NPM config cache
      run: npm config set cache ./artifacts/bundle-win/__cache/npm/
    - name: Verify npm cache
      run: npm cache verify
    - name: Run tests on bundle
      run: bash ./test-all.sh
      working-directory: artifacts/bundle-win/
      env:
        CYPRESS_CACHE_FOLDER: __cache/Cypress
      
