name: Build and Test Bundles

on:
  pull_request:
    branches: [ master ]

jobs:
  # Build the bundles
  bundle-win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: bash ./scripts/bundle-win.sh
    - name: Archive bundle
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Compress-Archive bundles/bundle-win bundle-win.zip
        azPSVersion: '3.1.0'
    - name: Upload bundle
      uses: actions/upload-artifact@v2
      with:
        name: bundle-win
        path: |
          bundle-win.zip

  # Test the bundles
  test-win:
    runs-on: windows-latest
    needs: bundle-win
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Download bundle
      uses: actions/download-artifact@v2
      with:
        name: bundle-win.zip
    - name: Unarchive bundle
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Expand-Archive -Path bundle-win.zip -DestinationPath ./bundle-win
    - name: Display contents of bundle
      run: ls -lah ./bundle-win
    - name: Run tests on bundle
      run: bash ./test.sh
      env:
        CYPRESS_CACHE_FOLDER: ./bundle-win/__sauce/__cache/Cypress
      
